[package]
name = "secret_generator"
version = "0.0.1"

[dependencies]
bincode = "1.2.1"
shrd_sec_lib = { path = "../.." }
clap = "2.33.0"
rpassword = "4.0.5"
text_io = "0.1.8"
secrecy = "0.6.0"
base64 = "0.12.0"
